@startuml entities

class User{
    + code
    + name
    + hasGroup(groupName)
}

note right of User::hasGroup
  Метод проверяет наличие группы,
  у пользователя используя [[https://www.npmjs.com/package/posix#posixgetgrnamgroup posixgetgrnamgroup]]
end note

class UserFactory {
    + getCurrentUser() : User
}

UserFactory - User : создает >

class RuUser extends User{
}

note right of RuUser
  Класс заполняет name, 
  используя транслитерацию
end note

@enduml
